name       : haskell-data-accessor-transformers
version    : 0.2.1.7
release    : 1
source     :
    - https://hackage.haskell.org/package/data-accessor-transformers-0.2.1.7/data-accessor-transformers-0.2.1.7.tar.gz : 20c8823dc16c7ca6f55c64eb5564c9aae4b5565406987a046ded2ea73618e07a
license    : BSD-3-Clause
component  : programming.haskell
summary    : Use Accessor to access state in transformers State monad
description: |
    Use Accessor to access state in transformers State monad
builddeps  :
    - haskell-cabal-install
    - haskell-data-accessor-devel
rundeps    :
    - devel:
        - haskell-data-accessor-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
